In [3]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.11.0


In [4]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255

11490434/11490434 [==============================] - 1s 0us/step


In [7]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)),
                                    tf.keras.layers.Dense(128, activation='relu'),
                                    tf.keras.layers.Dropout(0.2),
                                    tf.keras.layers.Dense(10)
                                   ])

In [8]:
predictions = model(x_train[:1]).numpy()

In [9]:
predictions

array([[ 0.40351412, -0.2411313 ,  0.24109012,  0.45823234, -0.18442912,
         0.7358134 ,  0.12899141,  0.37193206,  0.48417938, -0.12303852]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.11383943, 0.05974846, 0.09677269, 0.12024208, 0.06323422,
        0.15871151, 0.08651052, 0.11030032, 0.12340284, 0.06723784]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
loss_fn(y_train[:1], predictions).numpy()

1.8406671

In [13]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2911 - accuracy: 0.9151
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1430 - accuracy: 0.9574
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1052 - accuracy: 0.9686
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0862 - accuracy: 0.9738
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0750 - accuracy: 0.9765


In [15]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0725 - accuracy: 0.9785 - 518ms/epoch - 2ms/step


[0.07245786488056183, 0.9785000085830688]

In [16]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()
                                        ])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.0019682e-07, 5.7582690e-09, 1.9286417e-06, 1.7646749e-05,
        1.9825190e-12, 4.7983036e-08, 7.6719783e-13, 9.9997771e-01,
        2.6271278e-08, 2.4316691e-06],
       [2.8425475e-08, 4.1614636e-05, 9.9994123e-01, 1.2708328e-05,
        2.0758048e-15, 2.1670610e-06, 1.5957418e-08, 3.9062051e-15,
        2.2528134e-06, 6.9859236e-12],
       [3.6922970e-08, 9.9960071e-01, 1.5848404e-04, 1.8339533e-06,
        1.0610004e-05, 4.8614953e-07, 3.5320147e-06, 2.0492720e-04,
        1.9297107e-05, 1.0672018e-07],
       [9.9973673e-01, 1.0621293e-08, 9.2812406e-05, 2.9704881e-07,
        1.4389851e-06, 1.8126326e-05, 7.4728428e-05, 5.3067517e-05,
        8.4490610e-09, 2.2714463e-05],
       [3.5036899e-06, 6.0863345e-09, 6.2584409e-06, 2.8332954e-07,
        9.7216898e-01, 2.2493425e-07, 1.6151386e-06, 1.5498945e-04,
        4.4984836e-06, 2.7659608e-02]], dtype=float32)>